### ISSUE TITLE
Raspberry 1A+

### ISSUE THREAD

**Issue by KyomaHooin** [BouKiCHi/xmil#1]
ごめんください,

Raspberry 1A+では xmil エミュレータもいいですか。 十分ですか。
Raspberry 1A+では遅そすぎませんか。

ありがとう,

リチャさん

**Comment by BouKiCHi** [comment]
Raspberry Pi 3 Bでも重かったので、厳しいと思います。
他のエミュレータの方が良いかもしれません。

**Comment by KyomaHooin** [comment]
そうですか。他の エミュレータをやってみます。 ありがとうございました。 リチャさん。
